services:
  frontend:
    build: ./dsa_front
    ports:
      - "3000:3000"
    volumes:
      - ./dsa_front:/app
    entrypoint: ["sh", "-c", "npm install && npm start"]

  backend:
    depends_on:
      db:
        condition: service_healthy
    build: ./dsa_back
      # うまくいかなかったから仕方なくvolumesでマウント．本当はローカルに反映させたくないからCOPY使いたい．
      # context: .
      # dockerfile: dsa_back/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./dsa_back:/app
      - ./upload:/upload
      - ./resource:/resource
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: dsa 
      DATABASE_USER: dsa 
      DATABASE_PASSWORD: dsa-jikken 
      DATABASE_PORT: 3306

  judge:
    depends_on:
      db:
        condition: service_healthy
    build: ./dsa-judge
    ports:
      - "8080:8080"
    volumes:
      # ホスト環境のDockerサービスにアクセスするためのDockerソケットのマウント
      # 注) ホスト環境がUbuntuである必要あり
      - /var/run/docker.sock:/var/run/docker.sock
      # ソースコードのマウント
      - ./dsa-judge/src:/app
      # アップロードされたファイル用のディレクトリのマウント
      - ./upload:/upload
      # リソースディレクトリ(テストケース、サンプルプログラム等)のマウント
      - ./resource:/resource
      # ログディレクトリのマウント
      - ./dsa-judge/logs:/logs
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: dsa 
      DATABASE_USER: dsa 
      DATABASE_PASSWORD: dsa-jikken 
      DATABASE_PORT: 3306
      DOCKER_HOST: unix:///var/run/docker.sock
      TZ: Asia/Tokyo

  db:
    image: mysql:8.3
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - db-data:/var/lib/mysql
      - ./dsa_db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./dsa_db/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: dsa-root
      MYSQL_DATABASE: dsa
      MYSQL_USER: dsa
      MYSQL_PASSWORD: dsa-jikken
      TZ: Asia/Tokyo
    ports:
      - "3306:3306"

volumes:
  db-data:

