services:
  frontend:
    build: ./dsa-front
    ports:
      # ホストのlocalhost:3000番ポートをコンテナの3000番ポートにマッピング
      # 注意) デフォルトだとグローバルIPアドレスからアクセスできてしまうため，
      #       ホストのlocalhostのみにマッピングする
      - "127.0.0.1:3000:3000"
    volumes:
      - ./dsa-front:/app
      # ホストの./dsa-front/node_modulesをコンテナ内の/app/node_modulesに反映させないために、
      # コンテナ内の/app/node_modulesをAnonymous Volumeとしてマウント
      - /app/node_modules
    entrypoint: ["sh", "-c", "npm install && npm start"]

  backend:
    depends_on:
      db:
        condition: service_healthy
    build: ./dsa-back
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - ./dsa-back:/app
      # ホストの./dsa-back/.venvをコンテナ内の/app/.venvに反映させないために、
      # コンテナ内の/app/.venvをAnonymous Volumeとしてマウント
      - /app/.venv
      - ./upload:/upload
      - ./resource:/resource
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: dsa 
      DATABASE_USER: dsa 
      DATABASE_PASSWORD: dsa-jikken 
      DATABASE_PORT: 3306

  judge:
    depends_on:
      db:
        condition: service_healthy
    build: ./dsa-judge
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      # ホスト環境のDockerサービスにアクセスするためのDockerソケットのマウント
      # 注) ホスト環境がUbuntuである必要あり
      - /var/run/docker.sock:/var/run/docker.sock
      # ソースコードのマウント
      - ./dsa-judge:/app
      # ホストの./dsa-judge/.venvをコンテナ内の/app/.venvに反映させないために、
      # コンテナ内の/app/.venvをAnonymous Volumeとしてマウント
      - /app/.venv
      # アップロードされたファイル用のディレクトリのマウント
      - ./upload:/upload
      # リソースディレクトリ(テストケース、サンプルプログラム等)のマウント
      - ./resource:/resource
      # ログディレクトリのマウント
      - ./logs/dsa-judge:/logs
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: dsa 
      DATABASE_USER: dsa 
      DATABASE_PASSWORD: dsa-jikken 
      DATABASE_PORT: 3306
      DOCKER_HOST: unix:///var/run/docker.sock
      TZ: Asia/Tokyo

  db:
    image: mysql:8.3
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - db-data:/var/lib/mysql
      - ./dsa-db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./dsa-db/my.cnf:/etc/mysql/conf.d/my.cnf
      # バックアップのための、ダンプファイル共有ディレクトリ
      - ./backup:/backup
    environment:
      MYSQL_ROOT_PASSWORD: dsa-root
      MYSQL_DATABASE: dsa
      MYSQL_USER: dsa
      MYSQL_PASSWORD: dsa-jikken
      TZ: Asia/Tokyo
    ports:
      - "127.0.0.1:3306:3306"

volumes:
  db-data:

